[connections.postgresql]
# O Streamlit usa 'connections.postgresql' como nome padrão para este tipo de conexão
dialect = "postgresql"

# O host do seu banco de dados
host = "db.zxwpptscfqzhwpaapsez.supabase.co"

# A porta padrão do PostgreSQL
port = 5432

# O nome do banco de dados (o último 'postgres' na URI)
database = "postgres"

# O usuário do banco de dados (o primeiro 'postgres' na URI)
username = "postgres"

# Sua senha do banco de dados (Substitua [YOUR-PASSWORD] pela sua senha real)
password = "Pvprlz090287!"